### ISSUE TITLE
bcrypt dependencies

### ISSUE THREAD

**Issue by shakhal** [cgmartin/sailsjs-angularjs-bootstrap-example#24]
Thanks very much for this example.
I had trouble with bcrypt dependencies, 
upgrading to 0.8 seems to solve these issues though requires 
node version >= 0.11.x

**Comment by cgmartin** [comment]
Thanks @shakhal, the package.json has now been updated to use bcrypt 0.8.1. Though, it seems there is a build issue with bcrypt and the latest Node v0.12.0 version. Node versions < 0.12 seem to work, though.

**Comment by shakhal** [comment]
Thanks @cgmartin! Hope they fix these issues soon...
